text_to_find_on_last_run_null = "Ressarcimento de ICMS-ST"
table_container_id = "ConteudoPagina_tabContainerCaixaPostal_tabAtivas_ucItensAtivos_tabContainerCaixaPostal_tabMensagens"
pagination_container_id = "ConteudoPagina_tabContainerCaixaPostal_tabAtivas_ucItensAtivos_tabContainerCaixaPostal_tabMensagens_pager"
total_items_para_id = "ConteudoPagina_tabContainerCaixaPostal_tabAtivas_ucItensAtivos_tabContainerCaixaPostal_tabMensagens_lblTotalMensagens"


pdf_storage_path = r"C:\Bot_dec\Loja-CNPJ"
source_excel_file_path = r"C:\Bot_dec\dec_loja_cnpj.xlsx"
